### ISSUE TITLE
Search box does not work

### ISSUE THREAD

**Issue by roycyt** [daizutabi/mkdocs-ivory#1]
Hi,
Thank you for this great theme.
It seems that the search box does not work as expected.
From the debug console of Chrome, I see this error message:
```
Uncaught ReferenceError: base_url is not defined
    at main.js:93
```

**Comment by vagabond92** [comment]
This can be fixed by editing base.html to include the following:

<script>var base_url = '.';</script>

after line 97 in base.html I'll open a pull request.

**Comment by daizutabi** [comment]
Thank you for your advice.
I merged the pull request. Now it works fine.
