### ISSUE TITLE
Demo site?

### ISSUE THREAD

**Issue by DonaldTsang** [daizutabi/mkdocs-ivory#2]
Would like to see how this works

**Comment by daizutabi** [comment]
Not a demo site, but please visit [Pheasant Page](https://pheasant.daizutabi.net) which uses this theme.

**Comment by DonaldTsang** [comment]
If possible add this page link, and other pages that uses this theme into the ReadME.

**Comment by daizutabi** [comment]
I added the link into the ReadME. Thank you.
