### ISSUE TITLE
setup a conda-forge recipe

### ISSUE THREAD

**Issue by pkestene** [daizutabi/mkdocs-ivory#5]
Hello,

If I'm not mistaken, there's no recipe on conda-forge for your package.
Would you like to setup one ?

I've prepared a draft of recipe here : 
https://github.com/pkestene/staged-recipes/tree/recipe/mkdocs-ivory/recipes/mkdocs-ivory

what do you think ?

**Comment by daizutabi** [comment]
Thank you. I'd like to setup it. What should I do? I have no experience of conda-forge.

**Comment by pkestene** [comment]
I just followed the instructions : https://conda-forge.org/#add_recipe

In the recipe I put two maintainers (you and me), is that ok for you ?

The next step is just to submit a merge request from  https://github.com/pkestene/staged-recipes/tree/recipe/mkdocs-ivory/recipes/mkdocs-ivory
and wait if anything comes up from the test.

I guess it could be a good idea to do the same with your other package pheasant

**Comment by daizutabi** [comment]
OK. Welcome. Would you submit the merge request?

**Comment by pkestene** [comment]
Yes, here is the link:
https://github.com/conda-forge/staged-recipes/pull/11640

**Comment by pkestene** [comment]
FYI, it' been merged this morning:
https://github.com/conda-forge/mkdocs-feedstock

one can install it with
```shell
conda install -c conda-forge mkdocs-ivory
```

the next step could be to add a recipe for your other package pheasant. I can do it, but let me know if you prefer to do yourself.
